// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDze5yW6G4cKtNtBqG3MPLTCTOJGzWLHHI',
    appId: '1:210487299073:web:366c20986be292f4230400',
    messagingSenderId: '210487299073',
    projectId: 'ukrainian-d9d27',
    authDomain: 'ukrainian-d9d27.firebaseapp.com',
    storageBucket: 'ukrainian-d9d27.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB038YwFnmVJnc9LBupdTbZ3L2of04sQqg',
    appId: '1:210487299073:android:72785c1d0de04ee9230400',
    messagingSenderId: '210487299073',
    projectId: 'ukrainian-d9d27',
    storageBucket: 'ukrainian-d9d27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5pJtYvTaYkeXzRTHm5jal-GU-_Meco04',
    appId: '1:210487299073:ios:538e9b0e8edd990f230400',
    messagingSenderId: '210487299073',
    projectId: 'ukrainian-d9d27',
    storageBucket: 'ukrainian-d9d27.firebasestorage.app',
    iosBundleId: 'com.example.nesterov.ukrainian.ukrainian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5pJtYvTaYkeXzRTHm5jal-GU-_Meco04',
    appId: '1:210487299073:ios:538e9b0e8edd990f230400',
    messagingSenderId: '210487299073',
    projectId: 'ukrainian-d9d27',
    storageBucket: 'ukrainian-d9d27.firebasestorage.app',
    iosBundleId: 'com.example.nesterov.ukrainian.ukrainian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDze5yW6G4cKtNtBqG3MPLTCTOJGzWLHHI',
    appId: '1:210487299073:web:422875d1cbdfecc7230400',
    messagingSenderId: '210487299073',
    projectId: 'ukrainian-d9d27',
    authDomain: 'ukrainian-d9d27.firebaseapp.com',
    storageBucket: 'ukrainian-d9d27.firebasestorage.app',
  );
}
